FROM ubuntu:18.04

RUN apt-get update && \
    apt-get install python-pip -y && \ 
    pip install redis && \
    pip install flask

#EXPOSE 80
 
ADD /vote /app

WORKDIR /app

CMD ["python","main.py"]
