apiVersion: v1
kind: Service
metadata:
    name: "myakscluster-7c64"
    labels:
        app: "myakscluster-7c64"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "myakscluster-7c64"